# -*- coding: utf-8 -*-
"""Financial analytics project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-SpZeR5wE1QVSha-yE3G1ePwSRTX2TWw

## Step-by-Step Project Code
Here’s a sample code to analyze the financial data from the provided CSV file:
"""

# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
data = pd.read_csv(r'/content/Financial Analytics data.csv')

data

shape=data.shape
print(shape)

# Display the first few rows of the dataset
data.head()

# Display the last few rows of the dataset
data.tail()

# Data Cleaning
# Remove rows with missing values in 'Sales Qtr - Crore' and 'Mar Cap - Crore'
data = data.dropna(subset=['Sales Qtr - Crore', 'Mar Cap - Crore'])

data.shape

# Convert columns to appropriate data types
data['Mar Cap - Crore'] = data['Mar Cap - Crore'].astype(float)
data['Sales Qtr - Crore'] = data['Sales Qtr - Crore'].astype(float)
data.head()

# @title Default title text
# Exploratory Data Analysis (EDA)
# Top 10 companies by Market Capitalization
top_companies = data.nlargest(10, 'Mar Cap - Crore')
plt.figure(figsize=(10, 6))
sns.barplot(x='Mar Cap - Crore', y='Name', data=top_companies)
plt.title('Top 10 Companies by Market Capitalization')
plt.xlabel('Market Capitalization (in Crore)')
plt.ylabel('Company Name')
plt.show()

# Scatter plot of Market Capitalization vs Sales
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Sales Qtr - Crore', y='Mar Cap - Crore', data=data)
plt.title('Market Capitalization vs Sales')
plt.xlabel('Sales (in Crore)')
plt.ylabel('Market Capitalization (in Crore)')
plt.show()

# Calculate Market Cap to Sales Ratio
data['Market Cap to Sales Ratio'] = data['Mar Cap - Crore'] / data['Sales Qtr - Crore']

# Analyze the distribution of the Market Cap to Sales Ratio
plt.figure(figsize=(10, 6))
sns.histplot(data['Market Cap to Sales Ratio'], bins=30, kde=True)
plt.title('Distribution of Market Cap to Sales Ratio')
plt.xlabel('Market Cap to Sales Ratio')
plt.ylabel('Frequency')
plt.show()